### ISSUE TITLE
Change Ticec paper for Third international workshop on Gerontechnology

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#109]

**Comment by Daniel0205** [comment]
Write a paper fot congress gerontechnology 2020.
Evidence:
![image](https://user-images.githubusercontent.com/24316482/94504001-60ddbc80-01cd-11eb-86e1-aaae6160599f.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
