### ISSUE TITLE
Subtest: Claves (WISC)

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#11]
Develop the subtest "Claves" for the WISC test

**Test Requirements:**
- Must allow to select between 'Test application' and 'Result register'
- For 'Test application' must shown a guide for the application and have a timer to measure test application time
- The time must start from 120 seconds
- The 'Result register' option must have two button (one for 'Claves A' and the other one for 'Claves B')
- In 'Claves A' there must be a table to guide scoring (the table is present in test guide) and a textfield to record score
- In 'Claves B' must have a textfield to record score
- At the end of the test the score have to be shown

**Testing functionality**
For testing purposes use https://psique-app.web.app/login following the next steps:
1. Use the user "1234" with password "1234" in the login
2. Click on "pruebas de inteligencia"
3. Click on "Wisc IV" and then click on "Empezar"
4. Click on "Claves"

**Notes**
- In 'Result register' it is only selectionable one (claves A or B) dependent of which one was applied to the patient

**Comment by DianaKToro** [comment]
Error muy repetitivo, la falta de la letra s en instrucciones 
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/8aee8c09-4d89-4d77-af7f-c3d447d0fb4c)

Must allow to select between 'Test application' and 'Result register'. Check!
For 'Test application' must shown a guide for the application and have a timer to measure test application time. Check!
The time must start from 120 seconds. Check!
The 'Result register' option must have two button (one for 'Claves A' and the other one for 'Claves B'). Check!
In 'Claves A' there must be a table to guide scoring (the table is present in test guide) and a textfield to record score. Check!
In 'Claves B' must have a textfield to record score. Check!
At the end of the test the score have to be shown. Check!

**Comment by DianaKToro** [comment]
se sugiere un botón de atrás para devolverse entre interfaces, ya que si quiero pasar de claves números A al B tengo que terminar y guardar y me manda a hacer nuevamente el paso a paso

**Comment by Shinku24** [comment]
A return button was added in case a miss-selection between claves A or B, the suggerence is invalid because the specialist only applies one of them (claves A or B) to the patient, so is not really necesary to return to the other. This information was added in issue description in the "notes" section.

**Comment by DianaKToro** [comment]
closed!
