### ISSUE TITLE
Subtest: Comprensión (WISC)

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#12]
Develop the subtest "Comprensión" for the WISC test

**Test Requirements:**
- Must show at the beginning the instructions for the test application
- Must allow to select from which reactive to start the test (stimulus 5 for ages between 12-16, stimulus 3 for ages between 9-11 and reactive 1 for ages between 6-8 or any possible intellectual disability).
- Losing one of the first two stimulus (5 and 6 starting in 5 or 3 and 4 starting in 3) must continue with the respective stimulus (4 or 2) and go backwards until two correct answers are given and then, return to the next respective stimulus.
- The test must stop with three consecutive wrong answers
- The test must have a guide for scoring the answer indicating what is a correct answer and what is a wrong answer
- The test must have a textfield to register patient answer and three buttons for scoring
- At the end of the test the results have to be shown

**Testing functionality**
For testing purposes use https://psique-app.web.app/login following the next steps:
1. Use the user "1234" with password "1234" in the login
2. Click on "pruebas de inteligencia"
3. Click on "Wisc IV" and then click on "Empezar"
4. Click on "Compresión"

**Comment by DianaKToro** [comment]
no funciona el botón

**Comment by Quimisagi** [comment]
- [X] Must show at the beginning the instructions for the test application
(Corrección ortográfico: la respuesta **del** paciente)
- [X] Must allow to select from which reactive to start the test (stimulus 5 for ages between 12-16, stimulus 3 for ages between 9-11 and reactive 1 for ages between 6-8 or any possible intellectual disability).
(Pues sólo veo estimulo 1 y 3)
- [X] Losing one of the first two stimulus (5 and 6 starting in 5 or 3 and 4 starting in 3) must continue with the respective stimulus (4 or 2) and go backwards until two correct answers are given and then, return to the next respective stimulus.
(Pues sólo lo probé con el 3 porque no veo el 5)
- [X] The test must stop with three consecutive wrong answers
- [X] The test must have a guide for scoring the answer indicating what is a correct answer and what is a wrong answer
- [X] The test must have a textfield to register patient answer and three buttons for scoring
(Aunque no tiene el textfield pero tiene los botones)
- [X] At the end of the test the results have to be shown

Estado: completado. Puede pasarse a closed.
