### ISSUE TITLE
Change on sidebar

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#122]
- [x] Change sidebar icons color to white
- [x] Change sidebar text to white
- [x] Change sidebar color to the same of the buttons of main page

**Comment by Quimisagi** [comment]
Revisado

![image](https://user-images.githubusercontent.com/26472514/98955493-f0fd6a00-24cc-11eb-89a3-2f03d1d52806.png)

Estado: completado. Listo para pasarse a close
