### ISSUE TITLE
Change WAIS and WISC main page buttons

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#123]
- [x] Arrange button distribution on main page of wisc and wais (text size, responsive)
- [x] Change size of buttons to all buttons to have the same size

**Comment by Quimisagi** [comment]
Revisado!

![image](https://user-images.githubusercontent.com/26472514/98955270-b0055580-24cc-11eb-9b58-8200f6d25999.png)

Estado: completado
