### ISSUE TITLE
Interface changes - 05/11/2020

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#126]
**Changes on Login:**
- New background image
- Deleted "remember me" checkbox
- Centred Login form
- Added Psique logo

**Changes on main page:**
- Changed "quirofanoTest" image

**Changes on Buttons**
- Changed text to not be in upperCase

**Changes on sideNav**
- Allow closing sidebar on clicking outside the sidebar
- Added logout
- Changed "save and exit" icon

**Changes on header (navBar)**
- Removed logout from navbar
- Added padding to Psique logo

**Changes on Wais and wisc**
- Changed "cancelar" "calcular puntuación escalar" buttons colors
- Changed text component (<'p> and <'h1>) to typography
- Separated text, subtest buttons, and bottom buttons into grids
- Changed <div> component from subtest buttons mapping to <grid item>
- Fixed padding

**Comment by Quimisagi** [comment]
¡Revisado!
![image](https://user-images.githubusercontent.com/26472514/98955042-75032200-24cc-11eb-93a3-0802dca188c9.png)

![image](https://user-images.githubusercontent.com/26472514/98955185-9b28c200-24cc-11eb-954c-3b643c38edf1.png)

![image](https://user-images.githubusercontent.com/26472514/98955270-b0055580-24cc-11eb-9b58-8200f6d25999.png)


Estado: Listo para pasarse a close
