### ISSUE TITLE
Subtest: Búsqueda de Símbolos (WISC)

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#13]
Develop the subtest "Búsqueda de Símbolos" for the WISC test

**Test Requirements:**
- Must allow to select between 'Test application' and 'Result register'
- For 'Test application' must shown a guide for the application and have a timer to measure test application time
- The time must start from 120 seconds
- For 'Result register' option there have to be two buttons, one for 'Busqueda de simbolos A' and the other one for 'Busqueda de simbolos B'
- Both 'Busqueda de simbolos A' and 'Busqueda de simbolos B' must have textfields for correct and incorrect answers for each corresponding pages
- At the end of the test the score have to be shown

**Testing functionality**
For testing purposes use https://psique-app.web.app/login following the next steps:
1. Use the user "1234" with password "1234" in the login
2. Click on "pruebas de inteligencia"
3. Click on "Wisc IV" and then click on "Empezar"
4. Click on "Búsqueda de símbolos"

**Comment by Quimisagi** [comment]
La redacción de las instrucciones puede mejorar, no es muy clara. También faltan tildes. Ojito con la ortografía

![Capture](https://user-images.githubusercontent.com/26472514/94764098-5e679800-0370-11eb-8e0f-105754ceb3f6.PNG)

Es un poco incómodo escribir, luego darle a siguiente con el mouse, y luego tener que volver a seleccionar el campo de texto, borrar el 0, y después repetir el mismo proceso. Mi recomendación es quitar el 0 que aparece por defecto y que el campo de texto esté seleccionado por defecto.

![Capture1](https://user-images.githubusercontent.com/26472514/94764665-8bb44600-0370-11eb-86d8-5e5a6879e710.PNG)

**Comment by Quimisagi** [comment]
¿Posible bug?
Si le hago "siguiente" habiendo dejado el campo en 0 o vacío se salta casi todas las preguntas y me hace al final sólo unas 4 en total.

**Comment by Quimisagi** [comment]
No sé si sea un error pero me da de resultado 0 (puse números random)
![image](https://user-images.githubusercontent.com/26472514/94767661-abe50480-0372-11eb-8b80-d7f775b1ebd5.png)

**Comment by Quimisagi** [comment]
Resultados:

- [x] Must allow to select between 'Test application' and 'Result register'
- [x] For 'Test application' must shown a guide for the application and have a timer to measure test application time
- [x] The time must start from 120 seconds
- [x] For 'Result register' option there have to be two buttons, one for 'Busqueda de simbolos A' and the other one for 'Busqueda de simbolos B'
- [x] Both 'Busqueda de simbolos A' and 'Busqueda de simbolos B' must have textfields for correct and incorrect answers for each corresponding pages
- [ ] At the end of the test the score have to be shown (No sé. Me da 0)
