### ISSUE TITLE
Develop the amplified conceptual model

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#131]
Develop the amplified conceptual model

Evidence:
![Relational Model Psique - amplified conceptual.png](https://images.zenhubusercontent.com/5ee592f55c24786a647ce62e/d82de32f-c274-40e2-a19a-27862a635726)

**Comment by Quimisagi** [comment]
Se mira bien. Le doy el visto bueno

Listo para pasarse a Closed.
