### ISSUE TITLE
Subtest: Información (WISC)

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#14]
Develop the subtest "Información" for the WISC test

**Test Requirements:**
- Must show at the beginning the instructions for the test application
- Must allow to select from which stimulus to start the test (stimulus 12 for ages between 12-16, stimulus 10 for ages between 9-11 and reactive 5 for ages between 6-8 or any possible intellectual disability).
- Losing one of the first two reactives (12 and 13 starting in 12 or 10 and 11 starting in 10 or 5 and 6 starting in 5) must continue with respective stimulus (11,9 or 4) and go backwards until two correct answers are given and then, return to the next respective stimulus.
- The test must stop with five consecutive wrong answers
- The test must have a guide for scoring the answer indicating what is a correct answer and what is a wrong answer
- The test must have a textfield to register patient answer and two buttons for scoring
- At the end of the test the results have to be shown

**Testing functionality**
For testing purposes use https://psique-app.web.app/login following the next steps:
1. Use the user "1234" with password "1234" in the login
2. Click on "pruebas de inteligencia"
3. Click on "Wisc IV" and then click on "Empezar"
4. Click on "Información"

**Comment by DianaKToro** [comment]
no funciona el botón

**Comment by Quimisagi** [comment]
- [x] Must show at the beginning the instructions for the test application
- [ ] Must allow to select from which stimulus to start the test (stimulus 12 for ages between 12-16, stimulus 10 for ages between 9-11 and reactive 5 for ages between 6-8 or any possible intellectual disability). (??? Sólamente hay estímulo 1 y 3)
- [ ] Losing one of the first two reactives (12 and 13 starting in 12 or 10 and 11 starting in 10 or 5 and 6 starting in 5) must continue with respective stimulus (11,9 or 4) and go backwards until two correct answers are given and then, return to the next respective stimulus.
- [x] The test must stop with five consecutive wrong answers
- [x] The test must have a guide for scoring the answer indicating what is a correct answer and what is a wrong answer
- [x] The test must have a textfield to register patient answer and two buttons for scoring
- [x] At the end of the test the results have to be shown
