### ISSUE TITLE
Subtest: Aritmética (WISC)

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#15]
Develop the subtest "Aritmética" for the WISC test

**Test Requirements:**
- Must show at the beginning the instructions for the test application
- Must allow to select from which reactive to start the test (reactive 12 for ages between 10-16, reactive 9 for ages between 8-9 and reactive 3 for ages between 6-7 or any possible intellectual disability).
- Losing one of the first two reactives (12 and 13 starting in 12, 9 and 10 starting in 9, 3 and 4 starting in 3) must continue with the corresponding reactive (11,8 or 2) and go backwards until two correct answers are given and then, return to the next respective reactive.
- The test must stop with four consecutive wrong answers
- The test must show the figure relacted to the reactive for reactive 1,2,3,4,5
- The test must have a textfield to register patient answer
- At the end of the test the results have to be shown

**Testing functionality**
For testing purposes use https://psique-app.web.app/login following the next steps:
1. Use the user "1234" with password "1234" in the login
2. Click on "pruebas de inteligencia"
3. Click on "Wisc IV" and then click on "Empezar"
4. Click on "Aritmetica"

**Comment by DianaKToro** [comment]
tampoco funciona el botón :(

**Comment by Quimisagi** [comment]
- [x] Must show at the beginning the instructions for the test application
- [x] Must allow to select from which reactive to start the test (reactive 12 for ages between 10-16, reactive 9 for ages between 8-9 and reactive 3 for ages between 6-7 or any possible intellectual disability).
- [x] Losing one of the first two reactives (12 and 13 starting in 12, 9 and 10 starting in 9, 3 and 4 starting in 3) must continue with the corresponding reactive (11,8 or 2) and go backwards until two correct answers are given and then, return to the next respective reactive.
- [x] The test must stop with four consecutive wrong answers
- [x] The test must show the figure relacted to the reactive for reactive 1,2,3,4,5
- [x] The test must have a textfield to register patient answer
- [x] At the end of the test the results have to be shown

Estado: completado. Puede pasarse a closed.
