### ISSUE TITLE
Subtest: Aritmética (WAIS)

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#18]
Develop the subtest "Aritmética" for the WAIS test

**Test Requirements:**
- Must show at the beginning the instructions for the test application
- Must allow to select from which reactive to start the test (reactive 6 for ages between 16-89 and reactive 1 for possible intellectual disability).
- The first stimulus shown must be the example.
- Losing one of the first two reactives (6 and 7) while starting in reactive 6 must continue with reactive 5 and go backwards until two correct answers are given and then, return to the next reactive (i.e. 7 or 8).
- The test must stop with three consecutive wrong answers
- The test must show the figure relacted to the reactive for reactive 1,2,3,4,5
- The test must have a textfield to register patient answer
- At the end of the test the results have to be shown

**Testing functionality**
For testing purposes use https://psique-app.web.app/login following the next steps:
1. Use the user "1234" with password "1234" in the login
2. Click on "pruebas de inteligencia"
3. Click on "Wais IV" and then click on "Empezar"
4. Click on "Aritmetica"

**Comment by DianaKToro** [comment]
no funciona el botón aritmética

**Comment by Quimisagi** [comment]
No sale nada. Al presionar el botón se queda en blanco.

**Comment by Quimisagi** [comment]
- [X] Must show at the beginning the instructions for the test application
- [X] Must allow to select from which reactive to start the test (reactive 6 for ages between 16-89 and reactive 1 for possible intellectual disability).
- [X] The first stimulus shown must be the example.
- [X] Losing one of the first two reactives (6 and 7) while starting in reactive 6 must continue with reactive 5 and go backwards until two correct answers are given and then, return to the next reactive (i.e. 7 or 8).
(Pues en realidad tuve que acertar 3 veces seguidas para pasar al 7)
- [X] The test must stop with three consecutive wrong answers
- [X] The test must show the figure relacted to the reactive for reactive 1,2,3,4,5
- [X] The test must have a textfield to register patient answer
- [X] At the end of the test the results have to be shown
