### ISSUE TITLE
Subtest: Búsqueda de Símbolos (WAIS)

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#19]
Develop the subtest "Búsqueda de Símbolos" for the WAIS test

**Test Requirements:**
- Must allow to select between 'Test application' and 'Result register'
- For 'Test application' must shown a guide for the application and have a timer to measure test application time
- The time must start from 120 seconds
- For 'Result register' there have to be two textfields (one for correct answers and the other for wrong answers) for each test page, with a total of 7 pages
- At the end of the test the score have to be shown

**Testing functionality**
For testing purposes use https://psique-app.web.app/login following the next steps:
1. Use the user "1234" with password "1234" in the login
2. Click on "pruebas de inteligencia"
3. Click on "Wais IV" and then click on "Empezar"
4. Click on "Búsqueda de símbolos"

**Comment by DianaKToro** [comment]
Falta la s en instrucciones
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/73c5ce61-e459-43e6-a5e4-a26696603bf1)
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/15d27f95-9bdb-4171-9534-4ff353aa0681)

Must allow to select between 'Test application' and 'Result register'. Check!
For 'Test application' must shown a guide for the application and have a timer to measure test application time. Check!
The time must start from 120 seconds. Check!
For 'Result register' there have to be two textfields (one for correct answers and the other for wrong answers) for each test page, with a total of 7 pages. Check!
At the end of the test the score have to be shown. Check!

**Comment by DianaKToro** [comment]
al darle click en el botón busqueda de simbolos ya no pasa nada, parece que le quitaron la escucha del botón

**Comment by Quimisagi** [comment]
Sigue sin tener las instrucciones...

![image](https://user-images.githubusercontent.com/26472514/97521756-374eb700-196c-11eb-835f-e45eeb5d9f64.png)

**Comment by Quimisagi** [comment]
- [x] Must allow to select between 'Test application' and 'Result register'
- [x] For 'Test application' must shown a guide for the application and have a timer to measure test application time
- [x] The time must start from 120 seconds
- [x] For 'Result register' there have to be two textfields (one for correct answers and the other for wrong answers) for each test page, with a total of 7 pages
- [x] At the end of the test the score have to be shown

Estado: completado. Listo para pasarse a Closed
