### ISSUE TITLE
Subtest: Puzles Visuales (WAIS)

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#21]
Develop the subtest "Puzles Visuales" for the WAIS test

**Test Requirements:**
- Must show at the beginning the instructions for the test application
- Must allow to select from which reactive to start the test (reactive 5 for ages between 16-89 and reactive 1 for possible intellectual disability).
- The first stimulus shown must be the example.
- Losing one of the first two reactives (5 and 6) while starting in reactive 5 must continue with reactive 4 and go backwards until two correct answers are given and then, return to the next reactive (i.e. 6 or 7).
- The test must stop with three consecutive wrong answers
- The test must show the corresponding stimulus image
- The test must have a textfield to register patient answer
- At the end of the test the results have to be shown

**Testing functionality**
For testing purposes use https://psique-app.web.app/login following the next steps:
1. Use the user "1234" with password "1234" in the login
2. Click on "pruebas de inteligencia"
3. Click on "Wais IV" and then click on "Empezar"
4. Click on "Puzles Visuales"

**Comment by DianaKToro** [comment]
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/2d28bf18-cb1c-4b93-a535-c2a830efa094) 
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/207039d8-5334-40a7-a7c7-677e536d7548)
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/54300628-335d-4ef7-b93e-9167e4c678bd)

error en la palabra puzle y falta una tilde en la palabra estímulo. Ademas de palabras sin espacio en la segunda imagen.

Must show at the beginning the instructions for the test application.  **CHECK!**
Must allow to select from which reactive to start the test (reactive 5 for ages between 16-89 and reactive 1 for possible intellectual disability).  **CHECK!**
The first stimulus shown must be the example.  **CHECK!**
Losing one of the first two reactives (5 and 6) while starting in reactive 5 must continue with reactive 4 and go backwards until two correct answers are given and then, return to the next reactive (i.e. 6 or 7).  **CHECK!**
The test must stop with three consecutive wrong answers  **CHECK!**
The test must show the corresponding stimulus image  **CHECK!**
The test must have a textfield to register patient answer  **CHECK!**
At the end of the test the results have to be shown  **CHECK!**

**Comment by Daniel0205** [comment]
Corrected!
Puzles is ok in spanish.

**Comment by Quimisagi** [comment]
- [x] Must show at the beginning the instructions for the test application
- [x] Must allow to select from which reactive to start the test (reactive 5 for ages between 16-89 and reactive 1 for possible intellectual disability).
- [x] The first stimulus shown must be the example.
- [x] Losing one of the first two reactives (5 and 6) while starting in reactive 5 must continue with reactive 4 and go backwards until two correct answers are given and then, return to the next reactive (i.e. 6 or 7).
- [x] The test must stop with three consecutive wrong answers
- [x] The test must show the corresponding stimulus image
- [x] The test must have a textfield to register patient answer
- [x] At the end of the test the results have to be shown

Estado: completado. Listo para pasarse a closed
