### ISSUE TITLE
Subtest: Información (WAIS)

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#23]
Develop the subtest "Información" for the WAIS test

**Test Requirements:**
- Must show at the beginning the instructions for the test application
- Must allow to select from which reactive to start the test (reactive 3 for ages between 16-89 and reactive 1 for possible intellectual disability).
- Losing one of the first two reactives (3 and 4) while starting in reactive 2 must continue with reactive 5 and go backwards until two correct answers are given and then, return to the next reactive (i.e. 4 or 5).
- The test must stop with three consecutive wrong answers
- The test must have a guide for scoring the answer indicating what is a correct answer and what is a wrong answer
- The test must have a textfield to register patient answer and two buttons for scoring
- At the end of the test the results have to be shown

**Testing functionality**
For testing purposes use https://psique-app.web.app/login following the next steps:
1. Use the user "1234" with password "1234" in the login
2. Click on "pruebas de inteligencia"
3. Click on "Wais IV" and then click on "Empezar"
4. Click on "Información"

**Comment by DianaKToro** [comment]
no funciona el botón

**Comment by Quimisagi** [comment]
- [X] Must show at the beginning the instructions for the test application
- [X] Must allow to select from which reactive to start the test (reactive 3 for ages between 16-89 and reactive 1 for possible intellectual disability).
- [X] Losing one of the first two reactives (3 and 4) while starting in reactive 2 must continue with reactive 5 and go backwards until two correct answers are given and then, return to the next reactive (i.e. 4 or 5).
- [X] The test must stop with three consecutive wrong answers
- [X] The test must have a guide for scoring the answer indicating what is a correct answer and what is a wrong answer
- [X] The test must have a textfield to register patient answer and two buttons for scoring
- [X] At the end of the test the results have to be shown

Estado: completado. Puede pasarse a closed.
