### ISSUE TITLE
Subtest: Clave de Números (WAIS)

### ISSUE THREAD

**Issue by Shinku24** [Daniel0205/Psique#25]
Develop the subtest "Clave de Números" for the WAIS test

**Test Requirements:**
- Must allow to select between 'Test application' and 'Result register'
- For 'Test application' must shown a guide for the application and have a timer to measure test application time
- The time must start from 120 seconds
- The 'Result register' option must have a textfield for record patient score
- At the end of the test the score have to be shown

**Testing functionality**
For testing purposes use https://psique-app.web.app/login following the next steps:
1. Use the user "1234" with password "1234" in the login
2. Click on "pruebas de inteligencia"
3. Click on "Wais IV" and then click on "Empezar"
4. Click on "Clave de números"

**Comment by DianaKToro** [comment]
Present login failures

![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/1c527059-baec-451a-b78e-8a68c11d4ac2)

**Comment by DianaKToro** [comment]
Must allow to select between 'Test application' and 'Result register'. Check!
For 'Test application' must shown a guide for the application and have a timer to measure test application time. Check!
The time must start from 120 seconds. Check!
The 'Result register' option must have a textfield for record patient score. Check!
At the end of the test the score have to be shown. Check!

**Comment by DianaKToro** [comment]
falta una letra en el texto resaltado

![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/01038503-fe37-4c0e-9ef7-3d4b62920e2e)

**Comment by DianaKToro** [comment]
el botón clave de numeros tampoco funciona

**Comment by Quimisagi** [comment]
- [X] Must allow to select between 'Test application' and 'Result register'
- [X] For 'Test application' must shown a guide for the application and have a timer to measure test application time
The time must start from 120 seconds
- [X] The 'Result register' option must have a textfield for record patient score
- [X] At the end of the test the score have to be shown

Estado: completado. Listo para pasarse a closed.
