### ISSUE TITLE
Subtest: Dígitos (WISC)

### ISSUE THREAD

**Issue by stebanca1998** [Daniel0205/Psique#29]
Develop the subtest "Dígitos" for the WISC test

**Comment by stebanca1998** [comment]
The subtest must allow to enter the patient's anserw and automatically chechk if is right or not with a score of 1 or 0 respectively.

The subtest ends after 2 consecutive points of 0 in an attempt. 

The subtest has 32 Stimulus (16 for direct order and 16 for inverse order) and 8 attemps for each pair of stimulus.

**Comment by Quimisagi** [comment]
La redacción de las instrucciones puede mejorar, no es muy clara. También faltan tildes. Ojito con la ortografía

![image](https://user-images.githubusercontent.com/26472514/94767977-b18f1a00-0373-11eb-9c86-79a3cbce92a9.png)

Es un poco incómodo escribir, luego darle a siguiente con el mouse, y luego tener que volver a seleccionar el campo de texto, borrar el 0, y después repetir el mismo proceso. Mi recomendación es quitar el 0 que aparece por defecto y que el campo de texto esté seleccionado por defecto.

![image](https://user-images.githubusercontent.com/26472514/94767983-b784fb00-0373-11eb-8fc2-2cdfb7d95085.png)

**Comment by Quimisagi** [comment]
**Estado:** completado. Disponible para pasar a Close.
