### ISSUE TITLE
Subtest: Letras y numeros(WAIS)

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#32]
Development subtest "Letras y numeros" (WAIS)

**Comment by Daniel0205** [comment]
The subtest consist in 10 stimulus and 3 tries per stimuli.

This subtest must start from 1st stimuli and 1st try.

The subtest must allow to enter digits and letters mentioned by patient.

The limit of answers allowed per stimuli is limitated by the number of digits and numbers of the stimuli.

The subtest ends after 3 scores of 0 in the same stimuli.

![image](https://user-images.githubusercontent.com/24316482/93958196-942ad200-fd1b-11ea-93d1-74f681153b9f.png)

**Comment by DianaKToro** [comment]
No sirve el botón letras y números
![imagen.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/e80d8cf4-6dff-41cf-93ec-ea3929abc88c)

**Comment by Daniel0205** [comment]
Corrected!
