### ISSUE TITLE
Subtest: Comprensión(WAIS)

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#33]
Develop the "Comprensión" subtest of WAIS test

**Comment by Daniel0205** [comment]
This subtest must allow to select the initial stimuli dependign of the patient's age: 1st or 5th Stimuli

The subtest must show a clue and some example answers where is scored with 0, 1 or 2.

The subtest ends after 3 consecutive points of 0.

The subtest has 36 Stimulus.

**The test must comply with "inversion":** if in any of the two initial stimuli, the patient obtains a score of 0 or 1, the previous stimuli must be applied in reverse order until two scores of 2 are obtained in a row. if two scores of 1 are obtained the test will return to the next stimulus from initially had a score of 0 or 1. In case of get to stimuli #1 without obtaining two scores of 2, the test will be ended and their final score will be 0.

Evidence:
![image](https://user-images.githubusercontent.com/24316482/93963307-6f862880-fd22-11ea-8a95-489f2dafc0ee.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
