### ISSUE TITLE
Subtest: Cancelación(WAIS)

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#34]
Develop the "Cancelación" subtest of WAIS test

**Comment by Daniel0205** [comment]
This Subtest must allow to enter the test application time, the right and wrong answers for the two stimulus.

Additionally it must provide a timer to count the application time.

The final score of each stmulus is the number of right answers less the number of wrong answers. In case of the subtraction is lower than 0, the scored of that stimlii must be 0.

Evidence:
![image](https://user-images.githubusercontent.com/24316482/93962267-0b626500-fd20-11ea-9847-4955bc742763.png)

**Comment by DianaKToro** [comment]
Falta de tilde en las siguientes palabras: 
idénticas, calificará, automáticamente 
![imagen.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/fe1b97f5-ed73-4b25-beb9-4f18bbc22225)

acepta otros valores diferentes a números
![imagen.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/d42b2936-a555-4026-97ae-07d0530aa81c)

- [ ] This Subtest must allow to enter the test application time, the right and wrong answers for the two stimulus.
- [ ] Additionally it must provide a timer to count the application time.
- [ ] The final score of each stmulus is the number of right answers less the number of wrong answers. In case of the subtraction is lower than 0, the scored of that stimlii must be 0.
