### ISSUE TITLE
Subtest: Balanzas(WAIS)

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#35]
Develop the "Balanzas" subtest of WAIS test

**Comment by Daniel0205** [comment]
This subtest must start in 4th Stimuli or 1st Stimuli in case of an intellectual disability.

The subtest must allow the selection of an answer corresponding to the options showed in the image.

The patients' answers must be only numbers.

The subtest ends after 3 consecutive points of 0.

The "Time over" advice must be show as follow:
-1st - 12th Stimuli:  20 seconds after show the stimuli
-13th - 27th Stimuli:  40 seconds after show the stimuli 

**The test must comply with "inversion":** if in any of the two initial stimuli, the patient obtains a score of 0, the previous stimuli must be applied in reverse order until two scores of 1 are obtained in a row. if two scores of 1 are obtained the test will return to the next stimulus from initially had a score of 0. In case of get to stimuli #1 without obtaining two scores of 1, the test will be ended and their final score will be 0.

Evidence:
![image](https://user-images.githubusercontent.com/24316482/93962972-9d1ea200-fd21-11ea-85d0-c2a0fcfaea14.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.

**Comment by DianaKToro** [comment]
Falta de tildes en:
calificará (instrucciones), automáticamente (instrucciones) 

- [ ] This subtest must start in 4th Stimuli or 1st Stimuli in case of an intellectual disability.
- [ ] The subtest must allow the selection of an answer corresponding to the options showed in the image.
- [ ] The patients' answers must be only numbers.
- [ ] The subtest ends after 3 consecutive points of 0.
- [ ] The "Time over" 
- [ ] The test must comply with "inversion"
