### ISSUE TITLE
Subtest: Figuras Incompletas(WAIS)

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#36]
Develop the "Figuras Incompletas" subtest of WAIS test

**Comment by Daniel0205** [comment]
This subtest must start in 4th Stimuli or 1st Stimuli in case of an intellectual disability.

The stimuli prior to the initial stimulus will be rated 1. For example, if we start at 5, the stimuli from 1-4 will have a score as 1.

This subtest muts allow to enter the score in each of the 24 Stimuli pressing the numbers 1 or 0 in the keyboard.

The test ends after 4  consecutive points of 0.

If any score is entered by the keyboard after 20 minutes the test must warn that the time is over.

**The test must comply with "inversion":** if in any of the two initial stimuli, the patient obtains a score of 0, the previous stimuli must be applied in reverse order until two scores of 1 are obtained in a row. if two scores of 1 are obtained the test will return to the next stimulus from initially had a score of 0. In case of get to stimuli #1 without obtaining two scores of 1, the test will be ended and their final score will be 0.

Evidence:
![image](https://user-images.githubusercontent.com/24316482/93962198-d9510300-fd1f-11ea-956f-6a305d30f57d.png)

**Comment by DianaKToro** [comment]
Falta de tildes en:
calificará (instrucciones), automáticamente (instrucciones) , estímulo subprueba (título)

- [ ] This subtest must start in 4th Stimuli or 1st Stimuli in case of an intellectual disability.
- [ ] The stimuli prior to the initial stimulus will be rated 1. For example, if we start at 5, the stimuli from 1-4 will have a score as 1.
- [ ] This subtest muts allow to enter the score in each of the 24 Stimuli pressing the numbers 1 or 0 in the keyboard.
- [ ] The test ends after 4 consecutive points of 0.
- [ ] If any score is entered by the keyboard after 20 minutes the test must warn that the time is over.
- [ ] The test must comply with "inversion":

**Comment by Daniel0205** [comment]
Corrected!
