### ISSUE TITLE
Subtest: Sucesión de numeros y letras (WISC)

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#37]
Develop the "Sucesión de numeros y letras" subtest of the WISC test

**Comment by Daniel0205** [comment]
The subtest consist in 10 stimulus and 3 tries per stimuli.

This subtest must start from 1st stimuli and 1st try.

The subtest must allow to enter digits and letters mentioned by patient.

The limit of answers allowed per stimuli is limitated by the number of digits and numbers of the stimuli.

The subtest ends after 3 scores of 0 in the same stimuli.

**The test must comply with "inversion":** if in any of the two initial stimuli, the patient obtains a score of 0, the previous stimuli must be applied in reverse order until two scores of 1 are obtained in a row. if two scores of 1 are obtained the test will return to the next stimulus from initially had a score of 0. In case of get to stimuli #1 without obtaining two scores of 1, the test will be ended and their final score will be 0.

Evidence:
![image](https://user-images.githubusercontent.com/24316482/93957405-d2bf8d00-fd19-11ea-8fc0-7f199751447d.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.

**Comment by DianaKToro** [comment]
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/bd65cdc3-eb39-402c-8558-1aa4ad0601fc)

tildes, letras mal escritas, el campo del ejemplo no escribe en mayuscula, EL CERO DEBE BORRARSE, no deberia dejar poner espacio

This subtest must start from 1st stimuli and 1st try. check!

The subtest must allow to enter digits and letters mentioned by patient. check!

The limit of answers allowed per stimuli is limitated by the number of digits and numbers of the stimuli. check!

The subtest ends after 3 scores of 0 in the same stimuli. check!

**Comment by Daniel0205** [comment]
corrected
Evidence:
![image](https://user-images.githubusercontent.com/24316482/94893321-80364d00-044c-11eb-8aa0-03364a0e2685.png)

- [ ] tildes
- [ ] letras mal escritas
- [ ] el campo del ejemplo no escribe en mayuscula
- [ ] EL CERO DEBE BORRARSE 
- [ ] no deberia dejar poner espacio

**Comment by DianaKToro** [comment]
Falta tilde en las siguientes palabras: 
continuación, deberá, después, deberá, estímulo, calificará, automáticamente, estímulo (títulos)

![imagen.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/cb6fd975-4090-46bc-9f5e-0e1070a23146) ![imagen.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/a7aac9e6-de10-47ba-9ade-3846ccefce71)

**Comment by Daniel0205** [comment]
Corregido!
