### ISSUE TITLE
Subtest: Figuras Incompletas (WISC)

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#38]
Develop the "Figuras Incompletas" subtest of the WISC test

**Comment by Daniel0205** [comment]
This subtest must allow to select  the initial stimuli dependign of the patient's age: 1st, 5th or 10th Stimuli

The stimuli prior to the initial stimulus will be rated 1. For example, if we start at 10, the stimuli from 1-9 will have a score of 1.

This subtest muts allow to enter the score in each of the 38 Stimuli pressing the numbers 1 or 0 in the keyboard. 

If any score is entered by the keyboard after 20 minutes the test must warn that the time is over.

**The test must comply with "inversion":** if in any of the two initial stimuli, the patient obtains a score of 0, the previous stimuli must be applied in reverse order until two scores of 1 are obtained in a row. if two scores of 1 are obtained the test will return to the next stimulus from initially had a score of 0. In case of get to stimuli #1 without obtaining two scores of 1, the test will be ended and their final score will be 0.

Evidence:
![image](https://user-images.githubusercontent.com/24316482/93948624-83229680-fd04-11ea-9f54-0eaff0fb45d7.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.

**Comment by DianaKToro** [comment]
Falta de tíldes en las palabras de las siguientes instrucciones y resultados:
calificará, automáticamente e ítem, la ultima palabra es un error frecuente de los resultados

- [ ] This subtest must allow to select the initial stimuli dependign of the patient's age: 1st, 5th or 10th Stimuli
- [ ] The stimuli prior to the initial stimulus will be rated 1. For example, if we start at 10, the stimuli from 1-9 will have a score of 1.
- [ ] This subtest muts allow to enter the score in each of the 38 Stimuli pressing the numbers 1 or 0 in the keyboard.
- [ ] The test ends after 5 consecutive points of 0.
- [ ] If any score is entered by the keyboard after 20 minutes the test must warn that the time is over.

**Comment by Daniel0205** [comment]
Corrected!
