### ISSUE TITLE
Subtest: Registros (WISC)

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#39]
Develop the "Registros" subtest of the WISC test

**Comment by Daniel0205** [comment]
This Subtest must allow to enter the test application time, the right and wrong answers for the two stimulus.

Additionally it must provide a timer to count the application time.

The final score of each stmulus is the number of right answers less the number of wrong answers. In case of the subtraction is lower than 0, the scored of that stimlii must be 0.

Evidence: 
![image](https://user-images.githubusercontent.com/24316482/93946187-33d96780-fcfe-11ea-9365-2e0a1c37875f.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.

**Comment by DianaKToro** [comment]
Falta de tíldes y letras en en:
todos loS, calificará, automáticamente  
![imagen.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/6c1db33f-4adf-47dd-a964-b72febe799ae)

Los campos permiten ingresar cosas diferentes a los números 
![imagen.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/da687cd2-828c-45e2-91e5-fdfece4e669d)

- [ ] This Subtest must allow to enter the test application time, the right and wrong answers for the two stimulus.
- [ ] Additionally it must provide a timer to count the application time.
- [ ] The final score of each stmulus is the number of right answers less the number of wrong answers. In case of the subtraction is lower than 0, the scored of that stimlii must be 0.

**Comment by Daniel0205** [comment]
Corrected! 
The field does only accept number.
