### ISSUE TITLE
Subtest: Pistas (WISC)

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#40]
Develop the "Pistas" subtest of the WISC test

**Comment by Daniel0205** [comment]
This subtest must allow to select the initial stimuli dependign of the patient's age: 1st or 5th Stimuli

The subtest must show a clue and some example answers where is scored with 1 or 0.

The subtest ends after 5 consecutive points of 0.

The subtest has 24 Stimulus.

**The test must comply with "inversion":** if in any of the two initial stimuli, the patient obtains a score of 0, the previous stimuli must be applied in reverse order until two scores of 1 are obtained in a row. if two scores of 1 are obtained the test will return to the next stimulus from initially had a score of 0. In case of get to stimuli #1 without obtaining two scores of 1, the test will be ended and their final score will be 0.

Evidence:
![image](https://user-images.githubusercontent.com/24316482/93957090-241b4c80-fd19-11ea-9ff4-7924a73c6663.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.

**Comment by Quimisagi** [comment]
Me deja subirle y bajarle el puntaje de cada item lo cual creo que no tiene mucho sentido.

![image](https://user-images.githubusercontent.com/26472514/94769194-126c2180-0377-11eb-8310-694b7aace14e.png)

**Comment by Quimisagi** [comment]
- [x] This subtest must allow to select the initial stimuli dependign of the patient's age: 1st or 5th Stimuli
- [x] The subtest must show a clue and some example answers where is scored with 1 or 0.
- [ ] The subtest ends after 5 consecutive points of 0.
_Funciona sólamente la primera vez. Cuando lo vuelves a intentar ya no funciona esto_


The subtest has 24 Stimulus.

- [ ] The test must comply with "inversion": if in any of the two initial stimuli, the patient obtains a score of 0, the previous stimuli must be applied in reverse order until two scores of 1 are obtained in a row. if two scores of 1 are obtained the test will return to the next stimulus from initially had a score of 0. In case of get to stimuli #1 without obtaining two scores of 1, the test will be ended and their final score will be 0.
_No entendí muy bien esto_

**Comment by Daniel0205** [comment]
Corrected!
