### ISSUE TITLE
Subtest: Conceptos con dibujos (WISC)

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#41]
Develop the "Conceptos con dibujos" subtest of the WISC test

**Comment by Daniel0205** [comment]
This subtest must allow to select the initial stimuli dependign of the patient's age: 1st, 5th or 7th Stimuli

The test must allow to enter the selected options of the patient writting the number ubicated below the option.

The limit of answers allowed per stimuli is limitated by the number so rows in the stimuli.

The patients' answers must be only numbers.

The subtest ends after 5 consecutive points of 0.


**The test must comply with "inversion":** if in any of the two initial stimuli, the patient obtains a score of 0, the previous stimuli must be applied in reverse order until two scores of 1 are obtained in a row. if two scores of 1 are obtained the test will return to the next stimulus from initially had a score of 0. In case of get to stimuli #1 without obtaining two scores of 1, the test will be ended and their final score will be 0.

Evidence:
![image](https://user-images.githubusercontent.com/24316482/93954970-5e361f80-fd14-11ea-9044-c2af9ba8219a.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.

**Comment by DianaKToro** [comment]
Hace falta tildar algunas palabras, la palabra estímulo en el título no está tildada
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/04f7cf13-11bc-4096-b2e3-d6467f69569b)

This subtest must allow to select the initial stimuli dependign of the patient's age: 1st, 5th or 7th Stimuli.  **CHECK!**

The test must allow to enter the selected options of the patient writting the number ubicated below the option.  **CHECK!**

The limit of answers allowed per stimuli is limitated by the number so rows in the stimuli.  **CHECK!**

The patients' answers must be only numbers.  **CHECK!**

The subtest ends after 5 consecutive points of 0. **CHECK!**

The test must comply with "inversion":  **CHECK!**

Error detectado:
el primer campo numérico siempre toma el valor cero, así se escriba otro valor en el
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/832a9fef-afde-4fb5-ba36-d51ed63b8fbb)

**Comment by Daniel0205** [comment]
Error detectado:
el primer campo numérico siempre toma el valor cero, así se escriba otro valor en el **Corrected!**

El campo se demora en cambiar pero cambia.

**Comment by DianaKToro** [comment]
Falta tílde en las siguientes palabras:
presentarán, característica, común, calificará, automáticamente, ítem (resultados) 

![imagen.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/2c882505-407b-420d-951d-52ce44eac741) 

No debería dejar insertar letras, ni simbolos 
![imagen.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/facc98f5-9b26-4751-bf61-6a9459ddbe3c)

Sigue tomando el primer valor como cero
![imagen.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/6fa4d087-72d1-4ff6-a800-9a9cf48894c8)

Sugerencia: El cero podría ser un placeholder
![imagen.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/cf21be1c-8aeb-4267-af00-847aa2e53ec8)

**Comment by Daniel0205** [comment]
Corrected!
