### ISSUE TITLE
Define database model 

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#48]
Design the data model for the persistence of psique

**Comment by Daniel0205** [comment]
Define relational data model for database of Psique

URL of the diagram:  https://app.lucidchart.com/invitations/accept/4e391cc4-bf6f-41de-a537-b26ccf678221

Evidence: 
![image](https://user-images.githubusercontent.com/24316482/93838197-704d8a80-fc4e-11ea-8957-44e7181dc7b9.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
