### ISSUE TITLE
Development Stroop Test

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#5]
Development of Stroop Test

**Comment by Daniel0205** [comment]
Development Stroop Test

**Comment by stebanca1998** [comment]
This test is divided into 3 subtests called: "Palabras", "Colores" and "Palabras-Colores".

For each subtest, the page has to shown a list of 100 items and must allow to press every item in orden to select the last item the patiens mentioned. Once is pressed the next page is show.

Once all subtests are done, the page has to show the results of the test, specially the interference.
