### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#56]
Develop the Login module

**Comment by Daniel0205** [comment]
Develop the login module, it must warn when the username o password is worng or loggin when is right.

Empty fields are not allowed.

Login: https://psique-app.web.app/login

Evidence:
![image](https://user-images.githubusercontent.com/24316482/93838541-97f12280-fc4f-11ea-9d52-8ebe5692f285.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
