### ISSUE TITLE
Resume Assessment

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#59]

**Comment by Daniel0205** [comment]
In the case of having an active assessment, the module must provide options to resume or close the saved assessment and start a new one.

in case of not having an active assesment the module must provide the option to create a new one. 

In case of having a saved assessment:
![image](https://user-images.githubusercontent.com/24316482/94394676-8a420e00-0123-11eb-9aa1-7818a6cb60f9.png)

In case of not having a saved assessment:
![image](https://user-images.githubusercontent.com/24316482/94394978-34219a80-0124-11eb-9f38-49756f556e1c.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
