### ISSUE TITLE
Rey Complex Figure Test

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#6]
Develop the Rey's Complex Figure test (The formulary for test result registration)

**Test Requirements:**
- Must allow to register date of application
- Must allow to register time of application
- Must have a textfield for copy type
- Must have a textfield for observations
- Must show the figure of the test as guide
- Must allow to indicate the if the part is absent (or not), the state (correct or incorrect) and if it is well located for each of the 18 parts
- The score will be shown in a confirmation dialog when click on save button

**Testing functionality**
For testing purposes use https://psique-app.web.app/login following the next steps:
1. Use the user "1234" with password "1234" in the login
2. Click on "pruebas de memoria"
3. Click on "Prueba de Rey"

**Comment by Quimisagi** [comment]
- [x] Must allow to register date of application
- [x] Must allow to register time of application
- [x] Must have a textfield for copy type
- [x] Must have a textfield for observations
- [x] Must show the figure of the test as guide
- [x] Must allow to indicate the if the part is absent (or not), the state (correct or incorrect) and if it is well located for each of the 18 parts
- [x] The score will be shown in a confirmation dialog when click on save button

Estado: completado. Listo para pasarse a closed

Observaciones: 
- se puede acomodar mejor la distribución de los textsfields
- una vez que haya presentado la preuba, el botón de "Prueba de rey" deja de funcionar y toca reiniciar la página para que vuelva a funcionar.
-  si pinchas primero "bien situada" y luego "ausente" el "bien situada" queda seleccionado.
