### ISSUE TITLE
Zung Test 

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#7]
Development Zung Test

**Comment by Daniel0205** [comment]
The test must allow to select the following answers for each statement and each option has a numerical value: 
-muy pocas veces (1 Point)
-Algunas veces (2 Point)
-Muchas veces (3 Point)
-Casi siempre (4 Point)

Then the test must show the diagnosing depending the following puntiations:

1. less than 28 points (ausencia de depresión)

1. between 28-41 points (depresión leve)

1. between 42-53 points (depresión moderada)

1. more than 53 (depresión grave)


![image](https://user-images.githubusercontent.com/24316482/93413600-3737a380-f865-11ea-9b6f-b4c767e3bd5d.png)

**Comment by Quimisagi** [comment]
"muy pocas veces" está con minúscula inicial mientras que lo demás está en mayúscula inicial.
