### ISSUE TITLE
Wada test

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#74]
Develop WADA test

**Comment by Daniel0205** [comment]
The test must be applied using two devices, one for the doctor and one for the patient.

The test must allow the selection of the type of test that will be applied:
- Evaluación preliminar a la cirugía
- Evaluación con hemisferio derecho anestesiado
- Evaluación con hemisferio izquierdo anestesiado

The test must allow the selection of the subtest that will be applied.
Subtest:
- Conteo: The instruction "cuente del 1..20" must be show both patient's and doctor's device. The doctor must be able to score the subtest with 1 or 0.
During this first test the doctor must be able to register the moment when the hemisphere is anesthetized and if any event happend.

- Denominacion: 6 images are showed in both patient's and doctor's device and the doctor must be able to score if the patient said the right or wrong name of the object in the image.

- Seguimiento de instrucciones verbales: Instruccion are showed in in doctor's device and the screen of the patient device must be clear. the doctor must be able to scrore if the patient did or didn't the action indicated by the instruccion.

- Repeticion:  Word are showed in doctor's device and the screen of the patient device must be clear. the doctor must be able to score if the patient said the word correctly.

- Lectura:  Words are showed in both patient's and doctor's device and the doctor must be able to score if the patient read the word correctly.

- Seguimiento de instrucciones: 3 images are showed in both patient's and doctor's device and the doctor must be able to answer 3 questions about the images and score the patient's answer.


Finall the test must provide a summary of the results

Doctor's device: 
![image](https://user-images.githubusercontent.com/24316482/93964816-33ed5d80-fd26-11ea-9c9e-02c7a912b4fd.png)

Patient's  device:
![image](https://user-images.githubusercontent.com/24316482/93965357-8f6c1b00-fd27-11ea-86d8-98520efd364a.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.

**Comment by DianaKToro** [comment]
error: inicie la prueba como doctor y mientras esperaba al paciente e ingresó con su dispositivo, sale el siguiente error

![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/9b851af3-9530-43b0-912e-9079e7ce0c1f)

**Comment by Daniel0205** [comment]
Corrected!

**Comment by Quimisagi** [comment]
No sé como conectar paciente y doctor xd
