### ISSUE TITLE
Define Multidimentional data model

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#80]

**Comment by Daniel0205** [comment]
Evidence:
![Relational Model Psique - Multidimentional](https://user-images.githubusercontent.com/24316482/100309466-f5b82880-2f78-11eb-82a5-1c72cb06073d.png)

**Comment by Quimisagi** [comment]
Se mira bien. Le doy el visto bueno

Listo para pasarse a Closed.
