### ISSUE TITLE
Search Method Scales

### ISSUE THREAD

**Issue by Daniel0205** [Daniel0205/Psique#9]
Find a way to implement scales in the tests

**Comment by stebanca1998** [comment]
The page must allow selecting the patient's birthday and according to that date calculate the scalar punctuatuion of the WISC or WAIS test

Once the button "Calcular" is pressed the page has to show:
- Sum of the scalar scores obtained in each test
- Verbal compression index
- Perceptual Reasoning Index
- Working Memory Index
- Processing Speed ​​Index
- CIT
